name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jimc047
          password: dckr_pat_v7-NN4FdapyZy8cZ01mqMETs7tA

      - name: Build and push Docker image
        env:
          DOCKER_IMAGE: jimc047/voice_freight_broker
        run: |
          # Build the image using docker-compose
          docker-compose -f docker-compose.yml build backend
          
          # Push the image to Docker Hub (already tagged as $DOCKER_IMAGE:latest due to image field)
          docker push $DOCKER_IMAGE:latest

      - name: Reset RunPod Instance
        run: |
          curl 'https://rest.runpod.io/v1/pods/mls4a7xawx5gd5/reset' \
            --request POST \
            --header 'Authorization: Bearer rpa_HASVIV376C6PZT3DUFDL1QKM9D0ZPI8BIDZB84XLeq3z15'
